### ISSUE TITLE
Crash on newer versions of Forge

### ISSUE THREAD

**Issue by Darkfiend009** [Team-Remastered/End-Remastered-Forge#15]
Forge: 39.0.17
End Remastered: 5.0.1

Log: https://pastebin.com/39iQfhyy

I am assuming Forge changed something with mixins in their newer versions. Crashes on initial Minecraft launch.

**Comment by maxmitchelson** [comment]
At first look, it doesn't seem like a conflict with the forge launcher but rather a compatibility problem with electrodynamics' mixins

**Comment by Darkfiend009** [comment]
They did just release an update. I bumped the forge version at the same time i updated Electrodynamics so that makes sense. Would you prefer i reported over there?

**Comment by maxmitchelson** [comment]
It probably wouldn't be a bad idea to also report it on their repository but I'll try to figure out the root of the conflict

**Comment by Darkfiend009** [comment]
Reported the issue on their discord

![image](https://user-images.githubusercontent.com/42146629/149335365-3024b4cd-c4a5-48b4-a4ed-a2a7c31849f5.png)
