### ISSUE TITLE
Structures Ignoring Config [1.18.1]

### ISSUE THREAD

**Issue by AllenSeitz** [Team-Remastered/End-Remastered-Forge#18]
Great mod and I enjoy playing with it! I like your 1.18 changes too.

Your structures seem to be ignoring your own config. For example here's a structure that has spawned outside of the Overworld even though I'm using the default config where the only dimension in the whitelist is the Overworld.

![image](https://user-images.githubusercontent.com/4514349/152640183-13e67409-62a5-483a-8fbd-fda19da6030f.png)

In this case the dimension is dimdungeons:dungeon_dimension (a void world) with a single biome (dimdungeons:biome_dungeon, category 'none').

Fortunately the consequence in this case is minor but I imagine it could be very bad for your structures to be spawning in people's mining dimensions, RS storage dimensions, or other pocket-space dimensions.

One possible cause could be that you have 'none' in your whitelisted biome categories and that the category whitelist is basically 'OR'ing with the dimension whitelist instead of 'AND'ing with it? I think this might be the case because I was unable to /locate your structures in the Nether and End. (I have no biome mods in those dimensions.)

**Comment by LunafeyLazuli** [comment]
I'm having the same issue with Blue Skies, can confirm

**Comment by 0gp** [comment]
in 1.17.1 the Castle generates in the Nether too.
not sure how to disable this.
any ideas?

**Comment by Jack-Bagel** [comment]
Update the mod to 1.18.2 and download The Lost Castle mod to fix the issue.

The Lost Castle: https://www.curseforge.com/minecraft/mc-mods/the-lost-castle
