### ISSUE TITLE
Default config entry is malformed in 1.18 & 1.16

### ISSUE THREAD

**Issue by someaddons** [Team-Remastered/End-Remastered-Forge#19]
https://github.com/Team-Remastered/End-Remastered-Forge/blob/8d592535a2cee1a96ca38812f999feb096904a45/src/main/java/com/teamremastered/endrem/config/ERConfig.java#L76

The default config is missing the opening brace [

**Comment by someaddons** [comment]
Forgot to mention: the malformed entry causes worldgen threads to stall and after a while the server crashes with a seemingly random tick timeout

**Comment by Jack-Bagel** [comment]
Fixed with commit c713f52 & 7a1f5d6
