### ISSUE TITLE
Lost Eye (Mineshaft Eye) not found with "Repurposed Structures" and/or "Better Mineshafts"

### ISSUE THREAD

**Issue by demon112** [Team-Remastered/End-Remastered-Forge#20]
The Repurposed Structures mod adds new variants of mineshafts along with other buildings and the Better Mineshafts revamps the vanilla mineshafts. I have searched 10+ mineshafts from each mod and I have not found the eye. There is a possibility I'm just that unlucky but I'm starting to think otherwise.

**Comment by Jack-Bagel** [comment]
We inject the eyes inside the vanilla loot tables and I'm pretty sure that both RS and BM use the vanilla loot tables as well. You're either very unlucky or you have another mod installed that overrides the vanilla loot table of the mineshaft after the eyes are injected. In both cases, this isn't an issue that we can handle on our side.
