### ISSUE TITLE
Server crash with cartographer.

### ISSUE THREAD

**Issue by skybix** [Team-Remastered/End-Remastered-Forge#24]
Server crash with cartographer.

forge - 36.2.34
endrem-5.0.2-R-1.16.5.jar

crash report
https://pastebin.com/eY8h6SDF

**Comment by Ivan-Khar** [comment]
should be fixed in [End Remastered R5.0.3 (1.16.5)](https://www.curseforge.com/minecraft/mc-mods/endremastered/files/3827554)
