### ISSUE TITLE
Crash on startup with 1.18.2

### ISSUE THREAD

**Issue by BeeIsYou** [Team-Remastered/End-Remastered-Forge#25]
Forge version 40.1.0, using multimc, no other mods
[Crash report](https://paste.ee/p/HcI9w)

**Comment by Jack-Bagel** [comment]
There is no 1.18.2 version for End Remastered at the moment. Trying to play on 1.18.2 with a 1.18.1 mod will crash your game.

**Comment by VastayanWings** [comment]
is a 1.18.2 version actually planned or maybe even already in work?
dont need an eta, just yes or no would be enough for me :)

**Comment by Jack-Bagel** [comment]
Currently working on the 1.18.2 version but I don't have much time, gotta study for my finals. The 1.18.2 version _should_ release in june.
