### ISSUE TITLE
End Remastered (endrem) encountered an error during the common_setup event phase

### ISSUE THREAD

**Issue by SheReyy** [Team-Remastered/End-Remastered-Forge#27]
Mc: 1.16.5
Forge: 36.2.33
ModVersion: 5.0.2r

Issue: I started the game and I got an error stating the EndRem encountered an error during the common_setup event phase. I restarted the game, and now it looks like all's fine, but still, it is an issue. 

Log file:
[Here](https://gist.github.com/IamRyan30/8a1db44ab9b198cd2b558a050c5c33a0).

This issue seems to come from [this](https://github.com/Team-Remastered/End-Remastered-Forge/blob/1.16.X/src/main/java/com/teamremastered/endrem/world/gen/OreGenHandler.java#L28) class file.

**Comment by Jack-Bagel** [comment]
Send the logs again since they are not available anymore.
