### ISSUE TITLE
Crash caused by Wandering Trader

### ISSUE THREAD

**Issue by SheReyy** [Team-Remastered/End-Remastered-Forge#28]
Mc 1.16.5
Forge 36.2.33
EndRem Version: 5.0.2-R-1.16.5

Got a crash from an Wandering Trader. Here's the [log](https://gist.github.com/IamRyan30/2188022ad80599c661dcd360f1896eaa). Anything can be done?

**Comment by Jack-Bagel** [comment]
Can you try to reproduce the crash with the latest 1.16.5 version (5.0.3) please.

**Comment by SheReyy** [comment]
Didn't knew there was a 5.0.3. 0_0 my launcher showed nothing. I'll check that, sorry for the trouble.

**Comment by SheReyy** [comment]
> Can you try to reproduce the crash with the latest 1.16.5 version (5.0.3) please.

Apparently, this wasn't fixed on endrem-5.0.3-R-1.16.5.jar. Here's a [crash](https://pastebin.com/C6wwe35G) I received from someone.

**Comment by Jack-Bagel** [comment]
Looks like the price of the map was too big, it was probably changed in the config. Using the original price would probably fix the crash.
