### ISSUE TITLE
Description: Exception in server tick loop

### ISSUE THREAD

**Issue by Jetpack-Cat** [Team-Remastered/End-Remastered-Forge#29]
1.16.5 Forge
Can you tell me what caused this? It looks like end remastered caused it, i'm not sure what specifically though. I was running around in a sonicraft mobius dimension from the mod sonicraft when this happened.

https://gist.github.com/Jetpack-Cat/6351f135701829c3013d66cab6ea6b0a

**Comment by Jack-Bagel** [comment]
The map tried to locate the Castle in another dimension, but since the castle only generates in the Overworld it returned an error since there's no null exception check. This is fixed in the latest versions.
