### ISSUE TITLE
[1.18] Cryptic Eye with Apotheosis

### ISSUE THREAD

**Issue by Charismara** [Team-Remastered/End-Remastered-Forge#33]
Is it possible to get the Cryptic Eye when Apotheosis is installed? Because i enchanted 2 Stacks of Books and didn't get one :S

**Comment by Shadows-of-Fire** [comment]
Based on what someone just showed up by my discord asking, I think the answer is no, it's not.  Likely whatever handling ER is doing doesn't work with apoth's enchanting menu.

ER could simply provide an infusion enchanting recipe for when Apotheosis is present, which keeps the interactivity with the table while being non-invasive.
