### ISSUE TITLE
Mod doesn't load in newer versions of forge,instead error appears

### ISSUE THREAD

**Issue by NieZabija** [Team-Remastered/End-Remastered-Forge#34]
image of error:
![image](https://user-images.githubusercontent.com/110615487/182868272-39cbc34c-9b10-4289-8162-4b33a4815eee.png)
crash report file:
[crash-2022-08-04_16.10.11-fml.txt](https://github.com/Team-Remastered/End-Remastered-Forge/files/9260441/crash-2022-08-04_16.10.11-fml.txt)

**Comment by gameo7** [comment]
I'm getting this same error. In the meantime, what version of forge does the mod work with?

**Comment by NieZabija** [comment]
ive heard that it crashes on forge version above 41.0.96 from comments,but haven't tested it myself.

**Comment by Jack-Bagel** [comment]
Fixed in the latest update
