### ISSUE TITLE
the end castle is not generated

### ISSUE THREAD

**Issue by ShonaEV** [Team-Remastered/End-Remastered-Forge#35]
hi, I wanted to ask if you know what mod end remastered 1.18.2 is conflicting with, since I'm using it with other dungeon mods and world generation that I had already used in previous versions such as 1.16.5, but the structures of the mod is not generated.
If you know anything about it, it would be very helpful.
P.S. Thanks a lot

**Comment by BlocksterA** [comment]
The structures were removed in the latest version, as well as all the items besides the eyes

**Comment by ShonaEV** [comment]
ok, where can I see a guide on how to enter the end then?

**Comment by BlocksterA** [comment]
It's litteraly normal except you use the eyes from endren

**Comment by ShonaEV** [comment]
a ok, thanks
