### ISSUE TITLE
Datapack Incompatibility | Fabric End Remastered & Ultris: Minecraft Boss Expansion

### ISSUE THREAD

**Issue by KavisKryptic** [Team-Remastered/End-Remastered-Forge#36]
There is an incompatibility with the datapack: "ULTRIS: Minecraft Boss Expansion" 

Attempting to use the item "Ominous Eye" results in being prompted that: "this eye doesn't want to be used"

Steps to reproduce:

1. Install the datapack mentioned above long with End Remastered
2. Use the command /function 1_splatus:ultris/admin_menu, navigate through Boss Items and click on Ominous Pearl
3. Right click Ominous Pearl; Prompted with "This eye doesn't want to be used"

Expected Behavior:

For it to float in place when used, and being prompted where the nearest "Sanctum" is, a structure by the datapack. It works properly when End Remastered isn't present

**Comment by Jack-Bagel** [comment]
You can enable the eyes of ender in the endrem config file, that should fix the issue. I'm not sure however how this problem occurs since my code only targets the ender eye.
