### ISSUE TITLE
End Portal Not Opened Properly

### ISSUE THREAD

**Issue by NyvexOfShadows** [Team-Remastered/End-Remastered-Forge#37]
![2022-08-24_11 36 57](https://user-images.githubusercontent.com/58571419/186461426-58ac152e-443d-4b50-b839-a200162d3e8b.png)

My 1.18.2 stronghold generated with some eyes already filled in. I just beat the Wither to put the last eye in, but for some reason the portal will not generate. I'm not sure what the issue is on the program side, but this seems like a critical fix to make or address.

**Comment by Jack-Bagel** [comment]
You need to replace the eyes of ender with one of the custom eyes. You can remove the vanilla eyes by right clicking on them with one of the eye Endremastered adds.
