### ISSUE TITLE
Item descriptions are too long

### ISSUE THREAD

**Issue by Azarilh** [Team-Remastered/End-Remastered-Forge#38]
The descriptions of the eyes are too long, it's impossible to read them as they go outside the screen. Am i the only one?

[Screenshot](https://twitter.com/Azarilh/status/1571938115950112768/photo/1)

**Comment by DanCodesRBX** [comment]
get a mod like [ToolTipFix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix), it makes it look a lot better

**Comment by Azarilh** [comment]
Oooh!!
Thank you!
