### ISSUE TITLE
Charm Incompatibility 1.18.2 

### ISSUE THREAD

**Issue by SmartBear02** [Team-Remastered/End-Remastered-Forge#39]
Loot chest in beekeepers and wood villager`s houses from charm mod contain loot from jungles, oceans or mineshaft loot. This makes  end remastered's eyes appear in those loot chest.

**Comment by Jack-Bagel** [comment]
That means they use Minecraft's loot tables in their chests, I can't do anything about it. The solution would be to ask them to make custom loot tables for the chests in their their villager's houses or use other loot tables that don't contain the eyes.
