### ISSUE TITLE
End Gate's jigsaw blocks are targeting non-existent template pools.

### ISSUE THREAD

**Issue by maxmitchelson** [Team-Remastered/End-Remastered-Forge#4]
### !! This is a copy of issue 17 on GitLab (opened by Telepathic Grunt) !! ###

When using the mod called Blame with End Remastered, Blame caught that there are a few pieces that failed to spawn in the End gate structure. Specifically, Blame will detect if a Jigsaw Block tried to reference a template pool that does not exist. Hopefully this will help! The info that Blame printed out are:

****************** Blame Report 1.9.2 ******************
Empty template pool found from : endrem:puzzle_corridor
The path represented by this is:  data/endrem/worldgen/template_pool/puzzle_corridor
The structure piece with a Jigsaw Block that is targeting an empty pool is: endrem:end_gate/puzzles/puzzle1_ice
Most common cause is that there is a typo in this path to the template pool which then points to a non-existent pool.
Please let the mod author know about this so they can double check the path to make sure it is correct.
****************** Blame Report 1.9.2 ******************
Empty template pool found from : endrem:end_gate
The path represented by this is:  data/endrem/worldgen/template_pool/end_gate
The structure piece with a Jigsaw Block that is targeting an empty pool is: endrem:end_gate/terminal/terminal
Most common cause is that there is a typo in this path to the template pool which then points to a non-existent pool.
Please let the mod author know about this so they can double check the path to make sure it is correct.

**Comment by Jack-Bagel** [comment]
Removed the End Gate from all maintained versions.
