### ISSUE TITLE
Accidentally Placed Then Broke a portal frame.

### ISSUE THREAD

**Issue by ghost** [Team-Remastered/End-Remastered-Forge#44]
I accidentally placed an eye in a portal frame while testing how it works in my server I broke it and replaced the portal frame but now it says the eye is already placed... How do I reset this?

**Comment by Eatham532** [comment]
You can take out an eye by right clicking with an empty hand.

**Comment by Jack-Bagel** [comment]
You misplaced the portal frame, it needs to be facing outward. Also, yo remove a vanilla eye of ender you need to be holding one of the custom eye.

**Comment by genesy** [comment]
so.. how do you reset it. i have a new portal frame without eyes but it still says it's placed.

**Comment by ghost** [comment]
> so.. how do you reset it. i have a new portal frame without eyes but it still says it's placed.

It's been a really long time since I solved the issue but these aren't correct solutions. It was something like restarting the server or editing some type of nbt data in the world file.  It might have even been a command? Point is I don't remember so goodluck lmao.

For a more descriptive way of putting it, the original portal frame was generated, I placed all the eyes into the portal frame then realized I wanted it to be closed for the other players on my server to open it. Upon breaking the portal and replacing it the game told me it was already open.

**Comment by Eatham532** [comment]
Yeh, sometimes your world might be a bit corrupt. This is something you should always watch out for when using and updating mods. It is always good to make backups. :)
