### ISSUE TITLE
Add compat for Yung's Better Strongholds

### ISSUE THREAD

**Issue by RandomGuy91** [Team-Remastered/End-Remastered-Forge#47]
Is there any way that you can add an option to disable the Yung's Better Stronghokd from generating or would the moderator for that mod have to do it? If you can do it that would be really useful!

**Comment by Jack-Bagel** [comment]
just remove Yung's better stronghold? I'm not sure I understand why you would want a config for that.

**Comment by RandomGuy91** [comment]
Oh, right I'm stupid. smh  Although, I did realize that the normal stronghold is spawning alongside the end gate way even tough I disabled it in the config. Is it supposed to do that? (sorry if I'm asking a stupid question, I have a very limited understanding of mods)

**Comment by Aceplante** [comment]
This seems to work fine with better strongholds. I put the eyes in and it opened as normal

**Comment by RandomGuy91** [comment]
Nevermind, I realised my idea won't work/isnt useful anyway
