### ISSUE TITLE
Server crash when using Chunk Pregenerator

### ISSUE THREAD

**Issue by HollishKid** [Team-Remastered/End-Remastered-Forge#53]
I have posted the following issue on the Chunk Pregenerator mod ([here](https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/issues/30#issuecomment-1585666984)) but was told to also post it here.

Is there anything you could do to solve [this server crash](https://pastebin.com/erijVSwQ)?

Thanks for considering this =)

**Comment by Jack-Bagel** [comment]
Should be fixed on the lastest version of The Lost Castle Mod. Structures are not part of End Remastered anymore.
