### ISSUE TITLE
Eyes spawning in chests where they're not supposed to spawn in

### ISSUE THREAD

**Issue by cobaltlol** [Team-Remastered/End-Remastered-Forge#62]
As the title says, the mod makes eyes spawn in chests they're not supposed to spawn in, such as the cold eye which is only made to spawn in igloo chests, it now spawns in other chests too and I haven't modified anything in the config files.

**Comment by Jack-Bagel** [comment]
Another mod probably uses the igloo's loot table for their chests, can't really do anything about it.
