### ISSUE TITLE
Не удалось войти в портал

### ISSUE THREAD

**Issue by R1V3R008L** [Team-Remastered/End-Remastered-Forge#70]
Я играю на сборке dawncraft где присутствует данный мод, мы нашли эндер портал, поместили все 12 глаз и портал открылся. Но когда я начал входить в него, то я проходил сквозь портал и никак не могу решить эту проблему

**Comment by Jack-Bagel** [comment]
Здравствуйте. Ваша проблема не связана с нашим модом, т.к. наш мод не меняет функциональности самого портала. На этом данный тикет закрывается. Удачи.
