### ISSUE TITLE
[1.21] NeoForgecrash with mod latest version

### ISSUE THREAD

**Issue by Periam** [Team-Remastered/End-Remastered-Forge#77]
The latest version of the mod made the game crash on start.

NeoForge 21.0.95
endrem-neoforge-1.21-5.3.2.jar
jei-1.21-neoforge-19.5.0.35.jar

[crash-2024-07-16_09.00.56-fml.txt](https://github.com/user-attachments/files/16248381/crash-2024-07-16_09.00.56-fml.txt)
[2024-06-26-3.log.gz](https://github.com/user-attachments/files/16248393/2024-06-26-3.log.gz)
[debug.log](https://github.com/user-attachments/files/16248395/debug.log)
[latest.log](https://github.com/user-attachments/files/16248396/latest.log)

**Comment by Jack-Bagel** [comment]
Does the problem persist if you delete the config?

**Comment by Periam** [comment]
I deleted the toml file and the game still crash
![image](https://github.com/user-attachments/assets/6ed62621-577c-4e45-86cc-5aaa9a28158b)

**Comment by VoidLeech** [comment]
Neoforged refactored some of the config code
https://github.com/neoforged/NeoForge/commit/4c4b8a5fef79976c8b857ea5f6bbeb741e4b0e60

**Comment by ZealousVult2283** [comment]
Yea im having this issue as well, anyone got a fix yet?

**Comment by Jack-Bagel** [comment]
playing with neoforge version 21.0.20-beta should work until I update the config

**Comment by Periam** [comment]
No longer using the MC version
